### ISSUE TITLE
Vectors do not work

### ISSUE THREAD

**Issue by DrDanon** [co1emi11er2/Handcalcs.jl#11]
I like this package and I am testing to see if I can use it in class together with Unitful. I hit several problems one is:
I use Jupyter in vscode
@handcalcs x = [1, 2];
@handcalcs a = x[1] * 2

MethodError: no method matching convert_subscript(::LaTeXStrings.LaTeXString; function_name::Bool, convert_unicode::Bool, env::Symbol)

The first command works, but the second gives the error above
@handcalcs x = [1, 2];
#@handcalcs a = x[1] * 2
<img width="83" alt="image" src="https://github.com/co1emi11er2/Handcalcs.jl/assets/17229155/b0d7d0a9-5e5c-4cf7-a1d0-c97ddafef140">

**Comment by co1emi11er2** [comment]
Good catch. I think the issue is my package is trying (somewhat) to do:
```julia
@latexdefine a = $x[1] * 2
```
This will error. However, this works:
```julia
@latexdefine a = $(x[1]) * 2
```

So I think it is just a matter of wrapping it in parenthesis correctly. I will try to find some time this week to fix this.

**Comment by co1emi11er2** [comment]
As far as Unitful goes, that should be coming soon. Latexify.jl has a fix for the bug I mention in the documentation. However, it is taking some time for them to release it. I have some good enhancements ready once they release the update.

**Comment by co1emi11er2** [comment]
Hi @DrDanon. I have released a patch for the bug mentioned above. Do you want to try out the new release and see if that fixes it?

**Comment by DrDanon** [comment]
It works well thank you.
