### ISSUE TITLE
Add julia functions

### ISSUE THREAD

**Issue by DrDanon** [co1emi11er2/Handcalcs.jl#13]
Another issue I have and you mention in the manual is that not all functions are covered. I have exp() which is not covered so it breaks @handcalcs. One solution is @handcalcs T = exp(-Σ_t * x) not_funcs = [exp] another one is sum(), I use @handcalcs a = sum(σ_t) not_funcs = [sum]

Is there a way for the package user to add all the needed functions??

I want the user (in my case a student) not to worrier about adding special functions to make @handcalcs work.

**Comment by co1emi11er2** [comment]
It looks like my set_handcalcs function is not working properly for that. I will fix, but I can add more common math functions to automatically pass over them. Do you have any else in mind? Here are the ones I have now:
![image](https://github.com/co1emi11er2/Handcalcs.jl/assets/143426779/f287a0dd-927a-4e77-baa0-bd1e70ff8393)

**Comment by DrDanon** [comment]
For now log() and log10(). I will be using special functions like first order Bessel, but I can use not_funcs = for now.
If you will have  a way to for the package user to extend the list this will be great.

**Comment by co1emi11er2** [comment]
Okay @DrDanon. I made the updates. You can see the docs give a little more detail on how to add specific functions. Let me know if this works for you.
![image](https://github.com/co1emi11er2/Handcalcs.jl/assets/143426779/24aad255-718e-4029-81d8-06a31be09061)
